default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: root

development:
  <<: *default
  database: rssreader_development
test:
  <<: *default
  database: rssreader_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>