default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: user
  password: password

development:
  <<: *default
  database: rssreader_development
test:
  <<: *default
  database: rssreader_test

production:
  <<: *default
  adapter: postgresql
  database: rssreader_production
  #url: <%= ENV['DATABASE_URL'] %>